### ISSUE TITLE
Test target SPM Dependencies aren't de-duplicated

### ISSUE THREAD

**Issue by diogobalseiro** [trinhngocthuyen/cocoapods-spm#112]
### What happened?

Hello.

Before explaining the issue I'm seeing, let me say thank you for this plugin. 🙏 
The lack of interoperability between Cocoapods and SPM is crazy, and is stranding many medium/large sized projects with Cocoapods unnecessarily. 

## Context

I've started using this plugin to migrate over 150 Cocoapods dependencies (most internal) to SPM, in my work project, and I've ran into an issue regarding test targets. I'm unsure how to proceed at this point.

I've setup a [sample repository](https://github.com/diogobalseiro/cocoapods-spm-sample.git), which is just a fork this repo with some minor modifications to the sample project. The aim is to provide a very easy and simple way to reproduce the problem I'm seeing.

The problem I'm seeing is when running the unit tests:

`Class _TtC8SwiftUIXP33_266C9A88B74B5500A763A7BF40B6456F12_AlertWindow is implemented in both /Users/diogo.balseiro/Library/.../EX.app/EX (0x1035fc640) and /Users/diogo.balseiro/Library/.../EX.app/PlugIns/EXTests.xctest/EXTests (0x111efc068). One of the two will be used. Which one is undefined.
`

The SPM dependencies that are imported to the test target are not correctly de-dupped and can result in undefined behaviour at runtime. In the example above, the spm dependency is `SwiftUIX`.

## Sample

The changes made to showcase the problem above are simply these:

1. Create a new test target local pod named `CommonTestsKit`. That pod depends on the spm `SwiftUIX` and another other remote cocoapod `MoonKit`:

```
Pod::CompactSpec.new do |s|
  s.name = "CommonTestsKit"
  s.spm_dependency "SwiftUIX/SwiftUIX"
  s.dependency "MoonKit"
end
```

A swift file containing some sample code. Lets pretend this code helps with some unit test related logic:

```
import SwiftUIX
import MoonKit

public let exAction = SwiftUIX.Action.init {}
public let moon = Moon(.distantFuture)
```

2. Next we add this new dependency to the EXTests target:

```
target "EXTests" do

  pod "CommonTestsKit", :path => "LocalPods/CommonTestsKit"

end
```

3. We can make a minor tweak to the actual `EXTests`, though I believe its not necessary:
```
func testExample() {

       let anotherAction = exAction

       NSLog("Action \(anotherAction.hashIdentifiable)")
   }
```

4. Run the unit tests and the issue appears in the console log.

## Notes

This problem happens with all SPM dependencies that are "shared" between the `EX` and `EXTests` targets, and do not happen for regular Cocoapods dependencies (like the` MoonKit` above). This is why this behaviour seems incorrect.

## Consequence

This problem would seem fairly innocuous but can result in flaky tests and undefined behaviour, particularly if the duplicated classes rely on static code, such as singletons. I've reproduced this problem in my work project resulting in two static shared singletons for the same class, breaking a test suite. (While singletons are a design pattern we tend to avoid, its not always possible)
This is preventing us from adopting the plugin further and migrating more classes, as we starting to reach test targets that need to import dependencies already present in the "main" targets of the app/frameworks.

Do you have a suggestion on how to fix/avoid this problem? 

Thanks in advance. 👍 

### Stack

```
   CocoaPods : 1.14.3
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin21]
    RubyGems : 3.2.15
        Host : macOS 14.6.1 (23G93)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /Users/diogo.balseiro/.rbenv/versions/3.0.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs @ 0e9ffc8846c31d5211dcb884a8bd268cc034405d

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/diogo.balseiro/.rbenv/versions/3.0.1/bin/pod
```

### Plugins

```
cocoapods-compact-spec   : 0.0.3
cocoapods-deintegrate    : 1.0.5
cocoapods-plugins        : 1.0.0
cocoapods-search         : 1.0.1
cocoapods-spm            : 0.1.6
cocoapods-trunk          : 1.6.0
cocoapods-try            : 1.2.0
cocoapods-xcconfig-hooks : 0.0.1
```

### Podfile

```ruby
platform :ios, "16.0"
linkage = (ENV["LINKAGE"] || :static).to_sym
use_frameworks! :linkage => linkage
puts "Using linkage: #{linkage}"

@checksum = "dummy-checksum-to-prevent-merge-conflicts"

plugin "cocoapods-spm"
plugin "cocoapods-xcconfig-hooks"

config_compact_spec(
  extra: ->(s) { s.ios.deployment_target = "16.0" }
)

config_cocoapods_spm(
  dont_prebuild_macros: true,
  default_macro_config: "debug"
)

target "EX" do
  pod "Logger", :path => "LocalPods/Logger"
  pod "CommonUI", :path => "LocalPods/CommonUI"
  pod "Services", :path => "LocalPods/Services"

  pod "Orcam", :macro => {
    :git => "https://github.com/trinhngocthuyen/orcam.git",
    :branch => "main"
  }
  pod "MacroCodableKit", :macro => {
    :git => "https://github.com/mikhailmaslo/macro-codable-kit",
    :tag => "0.3.0"
  }

  spm_pkg "SnapKit",
          :url => "https://github.com/SnapKit/SnapKit.git",
          :version => "5.7.1",
          :products => ["SnapKit-Dynamic"]
  spm_pkg "SwiftUIX", :git => "https://github.com/SwiftUIX/SwiftUIX.git", :tag => "0.1.9"
  spm_pkg "SwiftyBeaver", :git => "https://github.com/SwiftyBeaver/SwiftyBeaver.git", :tag => "2.0.0"
  spm_pkg "opentelemetry-swift",
          :git => "https://github.com/open-telemetry/opentelemetry-swift.git",
          :branch => "main",
          :products => ["OpenTelemetrySdk"]
  spm_pkg "GoogleMaps",
          :git => "https://github.com/googlemaps/ios-maps-sdk.git",
          :version => "8.4.0",
          :products => ["GoogleMaps", "GoogleMapsBase", "GoogleMapsCore"]
  spm_pkg "DebugKit", :path => "LocalPackages/debug-kit"
end

target "EXTests" do

  pod "CommonTestsKit", :path => "LocalPods/CommonTestsKit"

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete "IPHONEOS_DEPLOYMENT_TARGET"
    end
  end
end
```

**Comment by trinhngocthuyen** [comment]
Hi @diogobalseiro,

First of all, thank you for the very detailed and well-explain description.

I would say this duplicated-class problem is **universal to how dependencies are linked (statically or dynamically)**.
Even if with CocoaPods, this issue still happens. A typical example is when both App and Tests depends on a static framework, like following. Check out the demo at https://github.com/trinhngocthuyen/ios-demos/tree/main/shared-lib.
```
App               Tests
 |                 |
  ----- Logger----- 
       (static)
```
The problem, in this example, would have been resolved if Logger is rather dynamic.

So, I think it's more about how we structure the dependencies (what depends on what, and whether one is static or dynamic). Unfortunately, an SPM package product is **static by default** while a pod is dynamic by default. This explains why the issue surfaces more frequently in the context of SPM.

For in-house packages, possibly you can consider updating the [library type](https://developer.apple.com/documentation/packagedescription/product/library/librarytype) when appropriated.
For 3rd-party packages, it would be difficult to deal with at the moment. With CocoaPods, we can magically turn a pod into static or dynamic form easily due to the flexibility of ruby code (podspecs are ruby). But for SPM, there are very few actions we can take from the plugin side to modify the library type to make it works the way we want.

Hope the explanation above helps clear your doubts.

**Comment by diogobalseiro** [comment]
Hello.

Your explanation was helpful, it cleared some suspicions we had. 
We tried fiddling with the library type of our SPM dependencies but couldn't find the right configuration to fix the problem. 

Eventually we managed to avoid the problem altogether by not relying on the tests specs for certain dependency installations.

Thanks 🙏
