### ISSUE TITLE
[Bug] 'aws/auth/exports.h' file not found

### ISSUE THREAD

**Issue by Linkadi98** [trinhngocthuyen/cocoapods-spm#122]
### What happened?

As mention in the comments in #105, when building flutter app (ios platform) Swift Compiler cannot find the file exports.h in auth-c-auth library in the aws-crt-swift spm package. Note that only flutter build ios throws this error but Xcode works fine without any problems. When I check in the [aws-crt-swift](https://github.com/awslabs/aws-crt-swift), the lib links to another one which is [this commit](https://github.com/awslabs/aws-c-auth/tree/48d647bf43f8872e4dc5ec6343b0c5974195fbdd), exports.h file is there, but Swift Compiler keeps saying it cannot find this file.

### CocoaPods environment

```ruby 
# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

plugin "cocoapods-spm"

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  spm_pkg "AmplifyUILiveness",
  :url => "https://github.com/aws-amplify/amplify-ui-swift-liveness.git",
  :branch => "main",
  :products => ["FaceLiveness"]
  
  spm_pkg "aws-crt-swift",
  :git => "https://github.com/awslabs/aws-crt-swift.git",
  :branch => "main",
  :products => ["AwsCommonRuntimeKit"]
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      config.build_settings['HEADER_SEARCH_PATHS'] << "$(SOURCE_PACKAGE_CHECKOUT_DIR)/aws-crt-swift/aws-c-auth/include"
    end
  end
end
```

### Anything else?

I use Xcode 16 and Flutter 3.24.4

**Comment by Linkadi98** [comment]
After some investications, I understand why Xcode build sucessfully but not for flutter, it's because of Xcode build from the swift packages right inside it, so it can find the exports.h file. But when flutter builds the app, it use the pods from .spm.pod folder which has something wrong here. I assume that the generated modulemap is missing something which can cause the swift compiler cannot find exports.h.

**Comment by trinhngocthuyen** [comment]
Thanks for the investigation & findings 👍.
Actually, the `.spm.pods` sandbox is just for the plugin to resolve dependencies and infer some metadata for the integration. Xcode or xcodebuild performs resolving packages independently (their checkouts are in DerivedData), which can later be used in the build process.
Not sure how Flutter build works. I'm new to Flutter, btw. Let me try setting up a sample Flutter project to reproduce the issue.

**Comment by Linkadi98** [comment]
Worth to note that Flutter is strongly coupling with Cocoapods. In the latest code of Flutter (on master/main branch), they have just announced the integration of SPM, but it is not stable. I think we have to wait until the next stable version to have a full support of SPM on Flutter. But yeah it's interesting to have a workaround. I still trying to get this but unfortunately no result yet.

**Comment by Linkadi98** [comment]
Hi @trinhngocthuyen, sorry for bother but when will this fix release? We are working on a project which has to write a flutter plugin like this issue, but without this fix we cannot continue. If the release plan follows strict rules, how can we build this plugin in local dev for quickly resolving our issue?

Btw many thanks again

**Comment by trinhngocthuyen** [comment]
I've just deployed a new version 0.1.6 that includes this fix. Kindly check it out. Thanks!
