### ISSUE TITLE
[Bug] plugin add two duplicate entry for spm dependency

### ISSUE THREAD

**Issue by wangzhizhou** [trinhngocthuyen/cocoapods-spm#123]
### What happened?

![image](https://github.com/user-attachments/assets/0e733ee6-2dab-4ac7-8b0f-f9e420470836)

### CocoaPods environment

cocoapods (1.16.2)
cocoapods-spm (0.1.5)

**Comment by trinhngocthuyen** [comment]
Hi @wangzhizhou,
There was a fix for package uniqueness in https://github.com/trinhngocthuyen/cocoapods-spm/pull/121.
Could you help try again with the latest on main?
Thank you!

**Comment by wangzhizhou** [comment]
> Hi @wangzhizhou, There was a fix for package uniqueness in #121. Could you help try again with the latest on main? Thank you!

ok, i will have a try with the main branch

**Comment by wangzhizhou** [comment]
I use the latest commit on main branch:

![image](https://github.com/user-attachments/assets/eefce09f-7f45-4a03-8702-a48f6e80c16a)

but the generated project as follow:

![image](https://github.com/user-attachments/assets/81b8f7ee-8581-4200-8050-bbeead6f8254)

The Test Demo project is: https://github.com/OrzGeeker/OrzSwiftMacros.git

```bash
cd AppDemo
DEV=1 bundle update 
DEV=1 bundle exec pod update 
xed .
```

**Comment by trinhngocthuyen** [comment]
@wangzhizhou I think there might be misconfiguration on your end in this case.

First, the plugin only operates on pod targets. It doesn't alter the main targets (AppDemo in the above example).
Moreover, it does **NOT** add packages to the **"Link Binary With Libraries"** section. Rather, the packages only appear in the "Target Dependencies" section.
So, I guess you might have added those packages to the main project by mistake.

<img width="777" alt="Screenshot 2024-11-18 at 13 40 11" src="https://github.com/user-attachments/assets/037be385-4b0a-48c0-bec4-3df5654e8dee">

<img width="804" alt="Screenshot 2024-11-18 at 13 39 52" src="https://github.com/user-attachments/assets/dfdafe27-a61a-4cdb-ba5e-59f7669953c2">

**Comment by wangzhizhou** [comment]
> @wangzhizhou I think there might be misconfiguration on your end in this case.
> 
> 
> 
> First, the plugin only operates on pod targets. It doesn't alter the main targets (AppDemo in the above example).
> 
> Moreover, it does **NOT** add packages to the **"Link Binary With Libraries"** section. Rather, the packages only appear in the "Target Dependencies" section.
> 
> So, I guess you might have added those packages to the main project by mistake.
> 
> 
> 
> <img width="777" alt="Screenshot 2024-11-18 at 13 40 11" src="https://github.com/user-attachments/assets/037be385-4b0a-48c0-bec4-3df5654e8dee">
> 
> 
> 
> <img width="804" alt="Screenshot 2024-11-18 at 13 39 52" src="https://github.com/user-attachments/assets/dfdafe27-a61a-4cdb-ba5e-59f7669953c2">
> 
> 
> 
> 

maybe I should check my Podfile, thank you

**Comment by trinhngocthuyen** [comment]
You can try removing MacroDemo from the "Link Binary With Libraries" section of AppDemo, followed by running pod install again. It should be good then.

**Comment by trinhngocthuyen** [comment]
I am closing this issue as a misconfiguration. Thank you!
