### ISSUE TITLE
[Bug] In Some Project, CocoaPods Install may add spm deps failed! because the pods_project is nil, and pod install crash

### ISSUE THREAD

**Issue by wangzhizhou** [trinhngocthuyen/cocoapods-spm#130]
### What happened?

![image](https://github.com/user-attachments/assets/49c5c27b-3d13-4957-9fb1-a8c21dcaacdd)

crash info as follow:

![image](https://github.com/user-attachments/assets/7c2be516-e190-45b3-8e94-d6bb5aa51ad6)

### CocoaPods environment

cocoapods 1.16.2 + ruby 3.2.0

### Anything else?

__No Response__

**Comment by trinhngocthuyen** [comment]
Hi there. Is it possible you can share the package declarations in Podfile?

**Comment by wangzhizhou** [comment]
maybe i will do some research to figure out the reason. there are so many private cocoapods plugins works in the project i am working on.

**Comment by wangzhizhou** [comment]
@trinhngocthuyen  does this usage is allowed: pod depend swift macro package:

![image](https://github.com/user-attachments/assets/c6250452-bea1-4904-9526-9e894cd7d99c)

**Comment by trinhngocthuyen** [comment]
Oh, you're using generate_multiple_pods_project. I'll check it out with this option then

**Comment by wangzhizhou** [comment]
I just comment off the `#install! 'cocoapods', :generate_multiple_pod_projects => true`, is works
