### ISSUE TITLE
[Feature Request] pod 'xxx', :macro => { ... } support use :path to specify the local swift package or macro

### ISSUE THREAD

**Issue by wangzhizhou** [trinhngocthuyen/cocoapods-spm#134]
### Motivation

Currently, the pod 'xxx', :macro => { ... } does not support  use :path to specify the local swift macro package:

![image](https://github.com/user-attachments/assets/147220a4-a514-4918-b2cc-5903af268706)

some project put their swift package on local disk with a mono repo development mode.
  

### Summary

use the pod 'xxx', :macro => { :path => '<local_swift_package_path>' } to resolve local swift package

**Comment by trinhngocthuyen** [comment]
A yes from me. This is indeed a valid request :). I'll plan for this change.

**Comment by trinhngocthuyen** [comment]
The support for local macro pod has been implemented in #138. Kindly help check it out. Thanks!
