### ISSUE TITLE
[Bug]Pod Dependency Error

### ISSUE THREAD

**Issue by mlch911** [trinhngocthuyen/cocoapods-spm#140]
### What happened?

I have many development pods. 
When I add spm_dependency [AsyncDNSResolver](https://github.com/apple/swift-async-dns-resolver) to Pod `A`. And Pod `B` dependency `A`. There will be build error in Pod `B`.
```
Missing required module 'AsyncDNSResolver'
```

**Comment by trinhngocthuyen** [comment]
Hey there.
I've tried adding AsyncDNSResolver to the example project on my end and it works.
Kindly refer to branch check/140, here's the diff: https://github.com/trinhngocthuyen/cocoapods-spm/compare/check/140

Could you help double-check the integration on your end?
If possible, would you mind sharing the package declarations (in Podfile) for troubleshooting?
Thank you!

**Comment by trinhngocthuyen** [comment]
Closing this issue as not reproducible. Feel free to reopen it with more details for troubleshooting. Thank you!
