### ISSUE TITLE
[Bug] cocapods-spm causing issues with react-native header search paths

### ISSUE THREAD

**Issue by ghedlund** [trinhngocthuyen/cocoapods-spm#36]
### What happened?

After installing cocoapods-spm and running pod install inside my react-native ios folder the project fails to compile with headers not found.  It seems the HEADER_SEARCH_PATHS lines are missing from the xconfigs for the pods in Pods/Target Support Files/<podname>.*.xcconfig.  Adding 

```
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/<podname>" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/<podname>"
```

to the xcconfig files does fix the issue.

Uninstalling cocopods-spm and running pod install again will fix this issue.

**Comment by trinhngocthuyen** [comment]
@ghedlund Thanks for reaching out!

Am I understanding correctly that the issue occurs after installing cocoapods-spm, without any usage from the plugin (ie. declaring spm packages), right?

**Comment by trinhngocthuyen** [comment]
Hi @ghedlund, I have made a fix for this issue. Would you mind trying again with version 0.1.1?
Thanks for the report 👍!

**Comment by ghedlund** [comment]
Just to confirm, I was not using any spm packages in that react-native project.  Thanks for the update - things are woking fine now.  And a big thank you for this project. you have saved me a lot of headache this week!
